/// Generated by Sideko (sideko.dev)
#[allow(unused)]
use crate::schemas::*;
/// Unifies the possible errors from exchange_code_for_key
#[derive(Debug, Clone)]
pub enum ExchangeCodeForKeyErrors {}
/// Unifies the possible errors from cli_check_updates
#[derive(Debug, Clone)]
pub enum CliCheckUpdatesErrors {}
/// Unifies the possible errors from stateless_generate_sdk
#[derive(Debug, Clone)]
pub enum StatelessGenerateSdkErrors {}
